async function main() {

}

main().catch(error => {
    process.exit(1);
});
